repos:
  - repo: local
    hooks:
      - id: block-commit-to-main
        name: Prevent Commits Directly to Main
        entry: python tools/prevent_commit_to_main.py
        language: system
        pass_filenames: false
        verbose: true
        always_run: true
        